export const employeeData = [
  {
    id: 1,
    name: "Kaja Husain",
    role: "MERN Stack Developer",
    attendance: "Present",
    checkIn: "09:10 AM",
    checkOut: "06:15 PM",
    workingHours: "9 hrs",
  },
  {
    id: 2,
    name: "Abhijith",
    role: "MERN Stack Developer",
    attendance: "Absent",
    checkIn: "",
    checkOut: "",
    workingHours: "-",
  },
  {
    id: 3,
    name: "Praveena",
    role: "React Developer",
    attendance: "Present",
    checkIn: "09:00 AM",
    checkOut: "06:00 PM",
    workingHours: "9 hrs",
  },
  {
    id: 4,
    name: "Sharookh",
    role: "Node.js Developer",
    attendance: "Present",
    checkIn: "09:25 AM",
    checkOut: "06:30 PM",
    workingHours: "8.5 hrs",
  },
  {
    id: 5,
    name: "Fasalu",
    role: "Node.js Developer",
    attendance: "Present",
    checkIn: "",
    checkOut: "",
    workingHours: "-",
  },
  {
    id: 6,
    name: "Jubair",
    role: "Flutter Developer",
    attendance: "Present",
    checkIn: "10:00 AM",
    checkOut: "06:45 PM",
    workingHours: "7.5 hrs",
  },
  {
    id: 7,
    name: "Pranav",
    role: "Project Manager",
    attendance: "Absent",
    checkIn: "",
    checkOut: "",
    workingHours: "-",
  },
];


export const internData = [
  {
    id: 1,
    name: "Aakash Rao",
    internRole: "Frontend Intern",
    attendance: "Present",
    checkIn: "09:35 AM",
    checkOut: "05:30 PM",
    workingHours: "7 hrs",
  },
  {
    id: 2,
    name: "Divya Nair",
    internRole: "UI Intern",
    attendance: "Present",
    checkIn: "10:00 AM",
    checkOut: "06:00 PM",
    workingHours: "6 hrs",
  },
  {
    id: 3,
    name: "Sanjay Pillai",
    internRole: "Backend Intern",
    attendance: "Absent",
    checkIn: "",
    checkOut: "",
    workingHours: "-",
  },
  {
    id: 4,
    name: "Tara Mishra",
    internRole: "HR Intern",
    attendance: "Present",
    checkIn: "09:50 AM",
    checkOut: "05:45 PM",
    workingHours: "7 hrs",
  },
  {
    id: 5,
    name: "Manoj Yadav",
    internRole: "Marketing Intern",
    attendance: "Present",
    checkIn: "",
    checkOut: "",
    workingHours: "-",
  },
  {
    id: 6,
    name: "Isha Kapoor",
    internRole: "Content Intern",
    attendance: "Present",
    checkIn: "09:20 AM",
    checkOut: "05:20 PM",
    workingHours: "7 hrs",
  },
  {
    id: 7,
    name: "Farhan Ali",
    internRole: "Testing Intern",
    attendance: "Absent",
    checkIn: "",
    checkOut: "",
    workingHours: "-",
  },
];

